### ISSUE TITLE
Scan Errors on new commits

### ISSUE THREAD

**Issue by krisrmgua** [Yelp/detect-secrets-server#24] opened 2019-03-12 16:17 UTC
After i add some repos, someone makes a commit and a **scan** no longer works. 
Gives this error:
`Traceback (most recent call last):
  File "/bin/detect-secrets-server", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/detect_secrets_server/__main__.py", line 39, in main
    return actions.scan_repo(args)
  File "/usr/lib/python2.7/site-packages/detect_secrets_server/actions/scan.py", line 31, in scan_repo
    exclude_lines_regex=args.exclude_lines,
  File "/usr/lib/python2.7/site-packages/detect_secrets_server/repos/base_tracked_repo.py", line 132, in scan
    self.storage.clone_and_pull_master()
  File "/usr/lib/python2.7/site-packages/detect_secrets_server/storage/base.py", line 83, in clone_and_pull_master
    git.pull_master(self._repo_location)
  File "/usr/lib/python2.7/site-packages/detect_secrets_server/storage/core/git.py", line 54, in pull_master
    'pull',
  File "/usr/lib/python2.7/site-packages/detect_secrets_server/storage/core/git.py", line 158, in _git
    stderr=subprocess.STDOUT
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', '--git-dir', '/root/.detect-secrets-server/repos/63944e2daa48f747b9f1ea33553843581ff20a6ab38f0830449bca703ec9b0085065b05e08c48f2a3ca545bf6b349778e80edec60aa8b34b1645c198b558badd', '--work-tree', '.', 'pull']' returned non-zero exit status 1`

I try running the git command its trying to run:

`[root@isr-secteam-scanner-1 ~]# git --git-dir /root/.detect-secrets-server/repos/63944e2daa48f747b9f1ea33553843581ff20a6ab38f0830449bca703ec9b0085065b05e08c48f2a3ca545bf6b349778e80edec60aa8b34b1645c198b558badd --work-tree . pull
From github.com:ps-dev/channels
 * branch            HEAD       -> FETCH_HEAD
Updating b5ef729..c2ee401
error: Your local changes to the following files would be overwritten by merge:
	common/commands/__specs__/delete-channel.spec.ts
	common/commands/__specs__/move-channel-content.spec.ts
	common/commands/add-content-to-channel/__specs__/course.spec.ts
	common/commands/add-content-to-channel/__specs__/interactive-course.spec.ts
	common/commands/add-content-to-channel/__specs__/path.spec.ts
	common/commands/add-content-to-channel/__specs__/project.spec.ts
	common/commands/add-content-to-channel/course.ts
	common/commands/add-content-to-channel/interactive-course.ts
	common/commands/add-content-to-channel/path.ts
	common/commands/add-content-to-channel/project.ts
	common/commands/delete-channel.ts
	common/commands/move-channel-content.ts
	common/commands/remove-content-from-channel/__specs__/course.spec.ts
	common/commands/remove-content-from-channel/__specs__/interactive-course.spec.ts
	common/commands/remove-content-from-channel/__specs__/path.spec.ts
	common/commands/remove-content-from-channel/__specs__/project.spec.ts
	common/commands/remove-content-from-channel/course.ts
	common/commands/remove-content-from-channel/interactive-course.ts
	common/commands/remove-content-from-channel/path.ts
	common/commands/remove-content-from-channel/project.ts
	common/publishers/channel-content-added.ts
	common/publishers/channel-content-removed.ts
	common/publishers/channel-content-updated.ts
Please, commit your changes or stash them before you can merge.
Aborting`

And the files that were changed in the latest commit are listed but it fails.  If i remove the repo and add it again the scan will work until the next commit. Not sure whats going on here.

**Comment by KevinHock** [comment] 2019-03-12 17:57
Hi @krisrmgua, thank you so much for the detailed bug report 👍 

I believe this is a duplicate of https://github.com/Yelp/detect-secrets-server/issues/21 which should be fixed pretty soon in the next version. (There’s a PR open now and I’ll release a new version tomorrow if it’s merged.)

**Closed by KevinHock** 2019-03-12 17:57 UTC

**Comment by KevinHock** [comment] 2019-03-13 19:36
Just wanted to follow up and say that due to #23 this should now be fixed in `0.2.7` https://github.com/Yelp/detect-secrets-server/blob/master/CHANGELOG.md#027

Thanks again for reporting this :)
